import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Tempo={tick:number;seconds:number;bpm:number};
type Scroll={startTick:number;endTick:number;multiplier:number};
type Point={tick:number;xFore:number;xRear:number};
type Lane={id:number;kind:string;points:Point[];colorId?:number;brightnessId?:number;beamWidthId?:number;beamShootPositionOffset?:number;isObliqueBeam?:boolean};
type Note={kind:string;tick:number;x:number;endTick?:number;endX?:number;isCritical?:boolean;laneId?:number;laneKind?:string;isRight?:boolean;bulletShape?:"Circle"|"Needle"|"Square";bulletStrength?:"Normal"|"Hard"|"Danger";bulletShooter?:string;bulletTarget?:string;bulletSpeed?:number;isLargeBullet?:boolean;bulletPlaceOffset?:number};
type Preview={durationSeconds:number;maxTick:number;resolution:number;measureCount:number;unknownCommandCount:number;tempos:Tempo[];scrollRanges:Scroll[];lanes:Lane[];notes:Note[]};
type EffectTextureFile={name:string;width:number;height:number;pngBase64:string};
type Bridge={chartPreview(path:string,root?:string):Promise<Preview>;chartAudio?(audio:unknown,root?:string):Promise<unknown>;chartSound?(name:string):Promise<unknown>;chartImage?(name:string):Promise<unknown>;chartEffectTextures?(root:string):Promise<EffectTextureFile[]>;thumbnail?(bundlePath:string,cache?:{gameRoot:string;kind:"music"}):Promise<string|null>};
type Snapshot={seconds:number;scrollSpeed:number};
type DisplayOptions={bell:boolean;side:boolean;floor:boolean;lanes:boolean;effects:boolean;bullets:boolean};
type Kind="tap"|"criticalTap"|"wall"|"criticalWall"|"holdLoop"|"holdEnd"|"flick"|"criticalFlick"|"bell"|"beamNotice"|"beamShot";
type Event={seconds:number;action:"play"|"start"|"stop";kind:Kind;voice?:string};

const api=()=>window.ogk as unknown as Bridge;
const files:Record<Kind,string>={tap:"se_tap.wav",criticalTap:"se_extap.wav",wall:"se_wall.wav",criticalWall:"se_exwall.wav",holdLoop:"se_hold.wav",holdEnd:"se_hold_end.wav",flick:"se_flick.wav",criticalFlick:"se_cr_flick.wav",bell:"se_bell.wav",beamNotice:"se_beam_notice.wav",beamShot:"se_beam_shot.wav"};
const volumes:Record<Kind,number>={tap:.52,criticalTap:.52,wall:.52,criticalWall:.52,holdLoop:.34,holdEnd:.52,flick:.52,criticalFlick:.52,bell:.52,beamNotice:.3,beamShot:.36};

function arrayBuffer(value:unknown){
  if(value instanceof ArrayBuffer)return value;
  if(ArrayBuffer.isView(value)){const v=value as ArrayBufferView;return v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength) as ArrayBuffer}
  const b=value as {type?:string;data?:number[]};
  if(b?.type==="Buffer"&&Array.isArray(b.data))return new Uint8Array(b.data).buffer;
  throw new Error("Electron 返回了无法识别的音频数据。");
}
function last<T>(items:T[],test:(item:T)=>boolean){let lo=0,hi=items.length;while(lo<hi){const m=lo+((hi-lo)>>1);if(test(items[m]))lo=m+1;else hi=m}return items[Math.max(0,lo-1)]}
function timing(preview:Preview){
  const resolution=Math.max(1,preview.resolution||1920);
  const tempos:Tempo[]=[];
  for(const point of [...(preview.tempos||[])].sort((a,b)=>a.tick-b.tick)){const previous=tempos.at(-1),bpm=Number.isFinite(point.bpm)&&point.bpm>0?point.bpm:(previous?.bpm||120),seconds=Number.isFinite(point.seconds)?point.seconds:(previous?previous.seconds+(point.tick-previous.tick)/resolution*240/previous.bpm:0);tempos.push({tick:point.tick,seconds,bpm})}
  if(!tempos.length)tempos.push({tick:0,seconds:0,bpm:120});
  const ranges=[...(preview.scrollRanges||[])].sort((a,b)=>a.startTick-b.startTick);
  const secondsAtTick=(tick:number)=>{const t=last(tempos,x=>x.tick<=tick);return t.seconds+(tick-t.tick)/resolution*240/t.bpm};
  const tickAtSeconds=(seconds:number)=>{const t=last(tempos,x=>x.seconds<=seconds);return t.tick+(seconds-t.seconds)*t.bpm/240*resolution};
  const scrollAtTick=(tick:number)=>{let p=secondsAtTick(tick)*60;for(const r of ranges){const a=Math.max(0,r.startTick),b=Math.min(tick,r.endTick);if(b>a)p+=(secondsAtTick(b)-secondsAtTick(a))*60*(r.multiplier-1)}return p};
  const scrollAtSeconds=(seconds:number)=>{const s=Math.max(0,seconds),tick=tickAtSeconds(s);let p=s*60;for(const r of ranges){const a=Math.max(0,r.startTick),b=Math.min(tick,r.endTick);if(b>a)p+=(secondsAtTick(b)-secondsAtTick(a))*60*(r.multiplier-1)}return p};
  return{resolution,secondsAtTick,tickAtSeconds,scrollAtTick,scrollAtSeconds};
}
function soundEvents(preview:Preview){
  const t=timing(preview),events:Event[]=[];
  const hit=(seconds:number,wall:boolean,critical:boolean)=>{events.push({seconds,action:"play",kind:wall?"wall":"tap"});if(critical)events.push({seconds,action:"play",kind:wall?"criticalWall":"criticalTap"})};
  preview.notes.forEach((n,i)=>{
    const start=t.secondsAtTick(n.tick),wall=n.laneKind==="LeftWall"||n.laneKind==="RightWall";
    if(n.kind==="Tap")hit(start,wall,!!n.isCritical);
    if(n.kind==="Hold"){hit(start,wall,!!n.isCritical);const voice="hold:"+i,end=Math.max(start,t.secondsAtTick(n.endTick||n.tick)-.5/60);events.push({seconds:start,action:"start",kind:"holdLoop",voice},{seconds:end,action:"stop",kind:"holdLoop",voice},{seconds:end,action:"play",kind:"holdEnd"})}
    if(n.kind==="Flick"){events.push({seconds:start,action:"play",kind:"flick"});if(n.isCritical)events.push({seconds:start,action:"play",kind:"criticalFlick"})}
    if(n.kind==="Bell")events.push({seconds:start,action:"play",kind:"bell"});
  });
  preview.lanes.filter(l=>l.kind==="Beam"&&l.points.length).forEach(l=>{const start=t.secondsAtTick(l.points[0].tick),end=t.secondsAtTick(l.points[l.points.length-1].tick),notice="beam-notice:"+l.id,shot="beam-shot:"+l.id;events.push({seconds:Math.max(0,start-45/60),action:"start",kind:"beamNotice",voice:notice},{seconds:Math.max(0,start-10/60),action:"stop",kind:"beamNotice",voice:notice},{seconds:Math.max(0,start-10/60),action:"start",kind:"beamShot",voice:shot},{seconds:end,action:"stop",kind:"beamShot",voice:shot})});
  return events.sort((a,b)=>a.seconds-b.seconds||(a.action==="stop"?-1:1));
}
function upper(events:Event[],seconds:number){let lo=0,hi=events.length;while(lo<hi){const m=lo+((hi-lo)>>1);if(events[m].seconds<=seconds)lo=m+1;else hi=m}return lo}

class Sounds{
  private context:AudioContext|null=null;
  private buffers=new Map<Kind,AudioBuffer>();
  private voices=new Set<{source:AudioBufferSourceNode;gain:GainNode;kind:Kind}>();
  private loops=new Map<string,{source:AudioBufferSourceNode;gain:GainNode;kind:Kind}>();
  private cursor=0;private previous=0;private rate=1;private volume=1;
  constructor(private events:Event[],private bridge:Bridge){}
  async prepare(){if(!this.bridge.chartSound)return false;this.context=new AudioContext({latencyHint:"interactive",sampleRate:48000});const kinds=[...new Set(this.events.map(e=>e.kind))];await Promise.all(kinds.map(async kind=>this.buffers.set(kind,await this.context!.decodeAudioData(arrayBuffer(await this.bridge.chartSound!(files[kind]))))));return this.buffers.size>0}
  async resume(){if(this.context?.state==="suspended")await this.context.resume()}
  setRate(rate:number){this.rate=rate;for(const v of this.voices)v.source.playbackRate.setValueAtTime(rate,this.context?.currentTime||0)}
  setVolume(volume:number){this.volume=volume;for(const v of this.voices)v.gain.gain.setValueAtTime(volumes[v.kind]*volume,this.context?.currentTime||0)}
  reset(seconds:number,restore:boolean){this.stopAll();this.cursor=upper(this.events,seconds);this.previous=seconds;if(!restore)return;const active=new Map<string,Kind>();for(let i=0;i<this.cursor;i++){const e=this.events[i];if(!e.voice)continue;if(e.action==="start")active.set(e.voice,e.kind);if(e.action==="stop")active.delete(e.voice)}for(const [id,kind] of active)this.start(id,kind)}
  advance(seconds:number){if(!this.context)return;if(seconds<this.previous||seconds-this.previous>.5){this.reset(seconds,true);return}while(this.cursor<this.events.length&&this.events[this.cursor].seconds<=seconds+.006){const e=this.events[this.cursor++];if(e.action==="play")this.play(e.kind);else if(e.action==="start"&&e.voice)this.start(e.voice,e.kind);else if(e.voice)this.stop(e.voice)}this.previous=seconds}
  stopAll(){for(const v of [...this.voices])try{v.source.stop()}catch{}this.voices.clear();this.loops.clear()}
  close(){this.stopAll();void this.context?.close();this.context=null}
  private voice(kind:Kind,loop:boolean){const buffer=this.buffers.get(kind);if(!buffer||!this.context)return null;const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=buffer;source.loop=loop;source.playbackRate.value=this.rate;gain.gain.value=volumes[kind]*this.volume;source.connect(gain).connect(this.context.destination);const voice={source,gain,kind};this.voices.add(voice);source.onended=()=>this.voices.delete(voice);return voice}
  private play(kind:Kind){const v=this.voice(kind,false);v?.source.start()}
  private start(id:string,kind:Kind){this.stop(id);const v=this.voice(kind,true);if(!v||!this.context)return;const requested=kind==="beamNotice"?.861:kind==="beamShot"?1.957:0;v.source.loopStart=Math.min(requested,Math.max(0,v.source.buffer!.duration-.02));v.source.loopEnd=v.source.buffer!.duration;v.gain.gain.setValueAtTime(0,this.context.currentTime);v.gain.gain.linearRampToValueAtTime(volumes[kind]*this.volume,this.context.currentTime+.008);this.loops.set(id,v);v.source.start()}
  private stop(id:string){const v=this.loops.get(id);if(!v||!this.context)return;this.loops.delete(id);const end=this.context.currentTime+.008;v.gain.gain.cancelScheduledValues(this.context.currentTime);v.gain.gain.setValueAtTime(v.gain.gain.value,this.context.currentTime);v.gain.gain.linearRampToValueAtTime(0,end);try{v.source.stop(end+.004)}catch{}}
}
function formatTime(seconds:number){const s=Math.max(0,seconds),m=Math.floor(s/60);return m+":"+(s-m*60).toFixed(1).padStart(4,"0")}

export function ChartPlayer({chart,music,root,onClose}:{chart:any;music:any;root:string;onClose():void}){
  const[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState("");
  const[playing,setPlaying]=useState(false),[audioReady,setAudioReady]=useState(false),[audioSettled,setAudioSettled]=useState(false);
  const[audioStatus,setAudioStatus]=useState("正在准备音轨…"),[soundReady,setSoundReady]=useState(false),[soundsEnabled,setSoundsEnabled]=useState(true);
  const[jacketUrl,setJacketUrl]=useState<string|null>(null),[soundSettled,setSoundSettled]=useState(false);
  const[rate,setRate]=useState(1),[scrollSpeed,setScrollSpeed]=useState(()=>Number(localStorage.getItem("chart-scroll-speed"))||6);
  const[musicVolume,setMusicVolume]=useState(80),[soundVolume,setSoundVolume]=useState(70);
  const[displayOptions,setDisplayOptions]=useState<DisplayOptions>({bell:true,side:true,floor:true,lanes:true,effects:true,bullets:false});
  const audioRef=useRef<HTMLAudioElement>(null),timelineRef=useRef<HTMLInputElement>(null),timeRef=useRef<HTMLSpanElement>(null),urlRef=useRef("");
  const durationRef=useRef(0),soundsRef=useRef<Sounds|null>(null),scrollRef=useRef(scrollSpeed),driftRef=useRef(0),autoplayRef=useRef(false);
  const clock=useRef({position:0,anchor:0,anchorMs:performance.now(),playing:false,rate:1});
  const current=useCallback(()=>{const c=clock.current;return c.playing?Math.min(durationRef.current,c.anchor+(performance.now()-c.anchorMs)/1000*c.rate):c.position},[]);
  const anchor=useCallback((seconds:number,active=clock.current.playing)=>{clock.current.position=seconds;clock.current.anchor=seconds;clock.current.anchorMs=performance.now();clock.current.playing=active},[]);
  const snapshot=useCallback(():Snapshot=>({seconds:current(),scrollSpeed:scrollRef.current}),[current]);
  const seek=useCallback((seconds:number)=>{const value=Math.max(0,Math.min(durationRef.current,seconds));anchor(value);if(audioReady&&audioRef.current)audioRef.current.currentTime=value;soundsRef.current?.reset(value,soundsEnabled&&clock.current.playing);if(timelineRef.current){timelineRef.current.value=String(value);timelineRef.current.style.setProperty("--timeline-progress",`${durationRef.current?value/durationRef.current*100:0}%`)}if(timeRef.current)timeRef.current.textContent=formatTime(value)+" / "+formatTime(durationRef.current)},[anchor,audioReady,soundsEnabled]);

  useEffect(()=>{let alive=true;autoplayRef.current=false;setSoundSettled(false);void api().chartPreview(chart.filePath,root).then(value=>{if(!alive)return;value.notes=[...(value.notes||[])].sort((a,b)=>a.tick-b.tick);const lanes=(value.lanes||[]).filter(lane=>lane&&Array.isArray(lane.points));value.lanes=lanes.length?lanes:[[-24,"LeftWall"],[-12,"Left"],[0,"Center"],[12,"Right"],[24,"RightWall"]].map(([x,kind],id)=>({id,kind,points:[{tick:0,xFore:x,xRear:x},{tick:value.maxTick,xFore:x,xRear:x}]} as Lane));value.scrollRanges=value.scrollRanges||[];durationRef.current=value.durationSeconds||0;setPreview(value);const engine=new Sounds(soundEvents(value),api());soundsRef.current=engine;void engine.prepare().then(ready=>{if(alive){setSoundReady(ready);setSoundSettled(true)}}).catch(()=>{if(alive){setSoundReady(false);setSoundSettled(true)}})}).catch(reason=>alive&&setError(reason instanceof Error?reason.message:"谱面读取失败。"));return()=>{alive=false;clock.current.playing=false;audioRef.current?.pause();soundsRef.current?.close();soundsRef.current=null}},[chart.filePath]);
  useEffect(()=>{let alive=true;setJacketUrl(null);const bundlePath=music?.jacket?.bundlePath;if(!bundlePath||!api().thumbnail)return()=>{alive=false};void api().thumbnail!(bundlePath,{gameRoot:root,kind:"music"}).then(image=>{if(alive)setJacketUrl(image)}).catch(()=>{if(alive)setJacketUrl(null)});return()=>{alive=false}},[music?.jacket?.bundlePath,root]);
  useEffect(()=>{let alive=true;setAudioReady(false);setAudioSettled(false);if(!music?.audio||!api().chartAudio){setAudioStatus("未找到乐曲音轨");setAudioSettled(true);return()=>{alive=false}}setAudioStatus("正在解码音轨…");void api().chartAudio!(music.audio,root).then(bytes=>{if(!alive)return;if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=URL.createObjectURL(new Blob([arrayBuffer(bytes)],{type:"audio/wav"}));if(audioRef.current){audioRef.current.src=urlRef.current;audioRef.current.load()}setAudioStatus("正在缓冲音轨…")}).catch(reason=>{if(alive){setAudioStatus(reason instanceof Error?reason.message:"音轨准备失败");setAudioSettled(true)}});return()=>{alive=false;if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=""}},[music?.audio]);
  useEffect(()=>{let frame=0;const update=()=>{let seconds=current();const c=clock.current,audio=audioRef.current,now=performance.now();if(c.playing&&audioReady&&audio&&!audio.paused&&now-driftRef.current>500){driftRef.current=now;if(Math.abs(audio.currentTime-seconds)>.05){seconds=audio.currentTime;anchor(seconds,true)}}if(timelineRef.current&&document.activeElement!==timelineRef.current){timelineRef.current.value=String(seconds);timelineRef.current.style.setProperty("--timeline-progress",`${durationRef.current?seconds/durationRef.current*100:0}%`)}if(timeRef.current)timeRef.current.textContent=formatTime(seconds)+" / "+formatTime(durationRef.current);if(c.playing&&soundsEnabled)soundsRef.current?.advance(seconds);if(c.playing&&durationRef.current>0&&seconds>=durationRef.current){c.playing=false;c.position=durationRef.current;audio?.pause();soundsRef.current?.stopAll();setPlaying(false)}frame=requestAnimationFrame(update)};frame=requestAnimationFrame(update);return()=>cancelAnimationFrame(frame)},[anchor,audioReady,current,soundsEnabled]);
  useEffect(()=>{const seconds=current();anchor(seconds);clock.current.rate=rate;if(audioRef.current)audioRef.current.playbackRate=rate;soundsRef.current?.setRate(rate)},[anchor,current,rate]);
  useEffect(()=>{scrollRef.current=scrollSpeed;localStorage.setItem("chart-scroll-speed",String(scrollSpeed))},[scrollSpeed]);
  useEffect(()=>{if(audioRef.current)audioRef.current.volume=musicVolume/100},[musicVolume]);
  useEffect(()=>{soundsRef.current?.setVolume(soundVolume/100)},[soundVolume]);

  const toggle=async()=>{if(!preview)return;if(clock.current.playing){const seconds=current();anchor(seconds,false);audioRef.current?.pause();soundsRef.current?.stopAll();setPlaying(false);return}let start=current();if(start>=durationRef.current-.01)start=0;anchor(start,true);const audio=audioRef.current;if(audioReady&&audio){audio.currentTime=start;audio.playbackRate=rate;try{await audio.play();anchor(audio.currentTime,true);setAudioStatus("音轨同步")}catch(reason){setAudioStatus(reason instanceof Error?reason.message:"音轨播放失败")}}if(soundsEnabled){await soundsRef.current?.resume();soundsRef.current?.setRate(rate);soundsRef.current?.reset(start,true)}setPlaying(true)};
  useEffect(()=>{if(!preview||!audioSettled||!soundSettled||autoplayRef.current)return;autoplayRef.current=true;void toggle()},[preview,audioSettled,soundSettled]);
  const close=()=>{clock.current.playing=false;audioRef.current?.pause();soundsRef.current?.stopAll();onClose()};
  const toggleSounds=()=>{const next=!soundsEnabled;setSoundsEnabled(next);if(!next)soundsRef.current?.stopAll();else if(clock.current.playing)soundsRef.current?.reset(current(),true)};
  const changeScrollSpeed=(amount:number)=>setScrollSpeed(value=>Math.max(1,Math.min(20,value+amount)));
  const changeRate=(amount:number)=>setRate(value=>Math.max(.5,Math.min(2,Number((value+amount).toFixed(1)))));
  const changeVolume=(setter:React.Dispatch<React.SetStateAction<number>>,amount:number)=>setter(value=>Math.max(0,Math.min(100,value+amount)));
  const toggleDisplay=(key:keyof typeof displayOptions)=>setDisplayOptions(value=>({...value,[key]:!value[key]}));
  const stepper=(label:string,value:string,decrease:()=>void,increase:()=>void,hint?:string)=><section className="parameter-stepper"><div><b>{label}</b>{hint&&<small>{hint}</small>}</div><div className="parameter-stepper-controls"><button onClick={decrease} aria-label={`降低${label}`}>−</button><output>{value}</output><button onClick={increase} aria-label={`提高${label}`}>+</button></div></section>;
  const duration=preview?.durationSeconds||0;
  return <div className="player-overlay" role="dialog" aria-modal="true" aria-label="谱面播放器"><section className="chart-player chart-player-electron">
    <aside className="player-info"><button className="player-close" onClick={close}>← 返回乐曲库</button><div className={jacketUrl?"player-jacket has-image":"player-jacket"}>{jacketUrl?<img src={jacketUrl} alt={`${music?.title||"乐曲"} 封面`} draggable={false}/>:music?.title?.slice(0,2)||"BM"}</div><h2>{music?.title||"未知乐曲"}</h2><p>{music?.artist||"—"}</p><div className="player-level"><b>{chart.difficultyName}</b><span>Lv. {chart.levelConstant}</span></div><dl><div><dt>谱面作者</dt><dd>{chart.creator||"未知"}</dd></div><div><dt>BPM</dt><dd>{chart.mainBpm||preview?.tempos?.[0]?.bpm||"—"}</dd></div><div><dt>总物量</dt><dd>{chart.totalNotes||preview?.notes?.length||"—"}</dd></div></dl><div className={"audio-state "+(audioReady?"ready":"")}><span>●</span><div><b>{audioStatus}</b><small>{soundReady?"游戏音效已加载":"游戏音效准备中或不可用"}</small></div></div></aside>
    <main className="player-stage"><div className="chart-board">{preview?<ChartCanvas preview={preview} snapshot={snapshot} displayOptions={displayOptions}/>:<span className="player-loading">{error||"正在解析谱面…"}</span>}</div><div className="player-timeline"><input ref={timelineRef} type="range" min="0" max={duration||1} step=".001" defaultValue="0" aria-label="谱面播放位置" onInput={e=>seek(Number(e.currentTarget.value))}/><span ref={timeRef}>0:00.0 / {formatTime(duration)}</span></div><div className="player-controls"><button onClick={()=>seek(0)} title="回到开头">↺</button><button onClick={()=>seek(current()-5)}>−5</button><button className="play" onClick={()=>void toggle()} disabled={!preview} aria-label={playing?"暂停":"播放"}>{playing?"Ⅱ":"▶"}</button><button onClick={()=>seek(current()+5)}>+5</button></div><audio ref={audioRef} preload="auto" onCanPlay={e=>{e.currentTarget.volume=musicVolume/100;setAudioReady(true);setAudioSettled(true);setAudioStatus("音轨已就绪")}} onError={()=>{setAudioReady(false);setAudioSettled(true);setAudioStatus("音轨加载失败")}}/></main>
    <aside className="player-options"><div className="option-title"><b>播放参数</b><span>{preview?"已加载":"读取中"}</span></div>{stepper("流速",scrollSpeed>=20?"SONIC":scrollSpeed.toFixed(2),()=>changeScrollSpeed(-.25),()=>changeScrollSpeed(.25),"原版 eSpeed")}{stepper("播放速度",`${rate.toFixed(1)}×`,()=>changeRate(-.1),()=>changeRate(.1),"0.5× – 2.0×")}<div className="option-stats"><span>小节数 <b>{preview?.measureCount?.toFixed(1)||"—"}</b></span><span>轨道数 <b>{preview?.lanes?.length||"—"}</b></span><span>未解释命令 <b>{preview?.unknownCommandCount??"—"}</b></span></div><section className="display-controls"><div className="section-title"><b>显示元素</b><small>点击开关</small></div><div className="element-toggle-grid">{([['bell','Bell'],['side','侧键'],['floor','地键'],['lanes','轨道'],['effects','特效'],['bullets','弹幕']] as const).map(([key,label])=><button key={key} className={displayOptions[key]?"element-toggle active":"element-toggle"} onClick={()=>toggleDisplay(key)} aria-pressed={displayOptions[key]}><i/> {label}</button>)}</div></section><section className="audio-controls"><div className="section-title"><b>音效调节</b></div>{stepper("音乐",`${musicVolume}%`,()=>changeVolume(setMusicVolume,-5),()=>changeVolume(setMusicVolume,5))}{stepper("音效",`${soundVolume}%`,()=>changeVolume(setSoundVolume,-5),()=>changeVolume(setSoundVolume,5))}<button className="sound-toggle" onClick={toggleSounds} aria-pressed={soundsEnabled}>音效预览 <i className={soundsEnabled&&soundReady?"":"off"}>●</i></button></section></aside>
  </section></div>
}

const colors:Record<string,string>={LeftWall:"#7e65ff",Left:"#ff4456",Center:"#30e179",Right:"#308bff",RightWall:"#ff46bc",Colorful:"#ffcd45",Beam:"#da4dff"};
const colorful=["#ff4456","#ff9d38","#ffd538","#81ed48","#30e1a4","#38d7ff","#477fff","#8d68ff","#ef67ff","#ff54ad","#a95a3d","#70e8d1","#eff5ff","#ffb5d0","#8470ff","#151922","#ff654d","#a8ed47","#55bfff","#ffe083"];
const spriteFiles=["mu3_nt_tap_00.png","mu3_nt_tap_02.png","mu3_nt_extap_00.png","mu3_nt_extap_02.png","mu3_nt_hold_00.png","mu3_nt_hold_02.png","mu3_nt_flicktap_00.png"] as const;
const shaderDrivenEffectTextures=new Set(["FX_hy_00_103","FX_hy_01_190"]);
const VW=1080,VH=1920,JUDGE=7.5,FAR=40,OFFSET_Y=190,MIN_PREVIEW_ZOOM=1.8;
function gameSpeed(v:number){return v>=20?30:1+(Math.max(1,Math.min(19.75,v))-1)*.27}
function laneX(lane:Lane,tick:number){const p=lane.points;if(!p.length)return 0;if(tick<=p[0].tick)return p[0].xFore;let lo=1,hi=p.length-1;while(lo<hi){const m=lo+((hi-lo)>>1);if(p[m].tick<tick)lo=m+1;else hi=m}const a=p[lo-1],b=p[lo];if(!b||b.tick===a.tick)return b?.xFore??a.xRear;return a.xRear+(b.xFore-a.xRear)*(tick-a.tick)/(b.tick-a.tick)}
function activeLane(lanes:Lane[],kind:string,tick:number){let active:Lane|undefined;for(const lane of lanes)if(lane.kind===kind&&lane.points.length&&tick>=lane.points[0].tick&&tick<=lane.points[lane.points.length-1].tick&&(!active||lane.points[0].tick>=active.points[0].tick))active=lane;return active}
function lowerNotes<T extends {tick:number}>(notes:T[],tick:number){let lo=0,hi=notes.length;while(lo<hi){const m=lo+((hi-lo)>>1);if(notes[m].tick<tick)lo=m+1;else hi=m}return lo}
function ChartCanvas({preview,snapshot,displayOptions,root=localStorage.getItem("ogk-toolbox.game-root.v1")||""}:{preview:Preview;snapshot():Snapshot;displayOptions:DisplayOptions;root?:string}){
  const ref=useRef<HTMLCanvasElement>(null),t=useMemo(()=>timing(preview),[preview]);
  const holdEnds=useMemo(()=>preview.notes.filter(note=>note.kind==="Hold").map(note=>({note,tick:note.endTick||note.tick})).sort((a,b)=>a.tick-b.tick),[preview]);
  const[sprites,setSprites]=useState<Record<string,HTMLImageElement>>({});
  const[effectSprites,setEffectSprites]=useState<Record<string,HTMLImageElement>>({});
  useEffect(()=>{let alive=true;const urls:string[]=[];if(!api().chartImage)return()=>{alive=false};void Promise.all(spriteFiles.map(async name=>{const url=URL.createObjectURL(new Blob([arrayBuffer(await api().chartImage!(name))],{type:"image/png"}));urls.push(url);const img=new Image();img.src=url;await img.decode();return[name,img] as const})).then(entries=>{if(alive)setSprites(Object.fromEntries(entries))}).catch(()=>{if(alive)setSprites({})});return()=>{alive=false;urls.forEach(URL.revokeObjectURL)}},[]);
  useEffect(()=>{let alive=true;const urls:string[]=[];setEffectSprites({});if(!root||!api().chartEffectTextures)return()=>{alive=false};void api().chartEffectTextures!(root).then(files=>Promise.all(files.map(async file=>{const binary=atob(file.pngBase64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:"image/png"}));urls.push(url);const img=new Image();img.src=url;await img.decode();return[file.name,img] as const}))).then(entries=>{if(alive)setEffectSprites(Object.fromEntries(entries))}).catch(()=>{if(alive)setEffectSprites({})});return()=>{alive=false;urls.forEach(URL.revokeObjectURL)}},[root]);
  useEffect(()=>{const canvas=ref.current,host=canvas?.parentElement,c=canvas?.getContext("2d",{alpha:false});if(!canvas||!host||!c)return;const reducedMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;let frame=0,dirty=true,lastSeconds=NaN,lastSpeed=NaN,w0=0,h0=0,d0=0;const observer=new ResizeObserver(()=>dirty=true);observer.observe(host);const tintedCache=new Map<string,HTMLCanvasElement>();
    const effectTexture=(name:string,color:string)=>{const image=effectSprites[name];if(!image)return null;const key=name+color,cached=tintedCache.get(key);if(cached)return cached;const surface=document.createElement("canvas");surface.width=image.naturalWidth;surface.height=image.naturalHeight;const context=surface.getContext("2d",{willReadFrequently:true});if(!context)return image;context.drawImage(image,0,0);const pixels=context.getImageData(0,0,surface.width,surface.height),data=pixels.data,values=new Float32Array(data.length/4);let min=1,max=0;for(let i=0,j=0;i<data.length;i+=4,j++){const value=Math.max(data[i],data[i+1],data[i+2])/255*(data[i+3]/255);values[j]=value;min=Math.min(min,value);max=Math.max(max,value)}const hex=color.startsWith("#")?color.slice(1):"ffffff",red=parseInt(hex.slice(0,2),16)||255,green=parseInt(hex.slice(2,4),16)||255,blue=parseInt(hex.slice(4,6),16)||255,floor=name==="FX_hy_01_190"?.32:min,range=Math.max(.001,max-floor);for(let i=0,j=0;i<data.length;i+=4,j++){const alpha=Math.pow(Math.max(0,(values[j]-floor)/range),1.18);data[i]=red;data[i+1]=green;data[i+2]=blue;data[i+3]=Math.round(alpha*255)}context.putImageData(pixels,0,0);tintedCache.set(key,surface);return surface};
    const stamp=(name:string,x:number,y:number,width:number,height:number,alpha:number,rotation=0,color="#ffffff")=>{if(shaderDrivenEffectTextures.has(name))return false;const image=effectTexture(name,color);if(!image)return false;c.save();c.translate(x,y);c.rotate(rotation);c.globalCompositeOperation="lighter";c.globalAlpha=Math.max(0,Math.min(1,alpha));c.drawImage(image,-width/2,-height/2,width,height);c.restore();return true};
    const projectZ=(z:number,x:number)=>{const dx=x*.1,dy=-4.75,dz=z+1,len=Math.hypot(8.25,26),fy=-8.25/len,fz=26/len,cy=dy*fz-dz*fy,cz=dy*fy+dz*fz;if(cz<=.3)return null;const tan=Math.tan(Math.PI/6),nx=dx/(cz*tan*(VW/VH)),ny=cy/(cz*tan);return{x:(nx+1)*VW/2,y:(1-ny)*VH/2+OFFSET_Y}};
    const draw=()=>{const state=snapshot(),w=host.clientWidth,h=host.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(!dirty&&Math.abs(state.seconds-lastSeconds)<.0001&&state.scrollSpeed===lastSpeed){frame=requestAnimationFrame(draw);return}dirty=false;lastSeconds=state.seconds;lastSpeed=state.scrollSpeed;if(w!==w0||h!==h0||dpr!==d0){w0=w;h0=h;d0=dpr;canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));canvas.style.width=w+"px";canvas.style.height=h+"px"}c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle="#04060b";c.fillRect(0,0,w,h);if(w<20||h<20){frame=requestAnimationFrame(draw);return}
      const currentTick=t.tickAtSeconds(state.seconds),scale=Math.min(w/VW,h/VH),ox=(w-VW*scale)/2,oy=(h-VH*scale)/2,logicalCenter=VW/2,previewZoom=MIN_PREVIEW_ZOOM,horizontalZoom=MIN_PREVIEW_ZOOM,zoomAnchorY=projectZ(JUDGE,0)?.y??VH*.82,backgroundHalfWidth=w/(scale*horizontalZoom);c.save();c.beginPath();c.rect(0,0,w,h);c.clip();c.translate(ox,oy);c.scale(scale,scale);c.translate(VW/2,zoomAnchorY);c.scale(horizontalZoom,previewZoom);c.translate(-logicalCenter,-zoomAnchorY);const bg=c.createLinearGradient(0,0,0,VH);bg.addColorStop(0,"#060912");bg.addColorStop(1,"#0c111d");c.fillStyle=bg;c.fillRect(logicalCenter-backgroundHalfWidth,0,backgroundHalfWidth*2,VH);
      const currentScroll=t.scrollAtSeconds(state.seconds),speed=gameSpeed(state.scrollSpeed),z=(tick:number)=>JUDGE+(t.scrollAtTick(tick)-currentScroll)*.2*speed,project=(tick:number,x:number)=>projectZ(z(tick),x);
      const tickAtZ=(lo:number,hi:number,target:number)=>{for(let i=0;i<28;i++){const m=(lo+hi)/2;if(z(m)<target)lo=m;else hi=m}return(lo+hi)/2},visibleStart=Math.max(0,currentTick-t.resolution),visibleEnd=z(preview.maxTick)<=FAR?preview.maxTick:tickAtZ(currentTick,preview.maxTick,FAR+.65);
      const wall=(kind:string,tick:number)=>activeLane(preview.lanes,kind,tick),bounds=(tick:number)=>{const a=wall("LeftWall",tick),b=wall("RightWall",tick);return[a?laneX(a,tick):-24,b?laneX(b,tick):24] as const};
      const ribbon=(left:{x:number;y:number}[],right:{x:number;y:number}[],fill:string,alpha:number)=>{if(left.length<2)return;c.save();c.globalAlpha=alpha;c.beginPath();c.moveTo(left[0].x,left[0].y);left.slice(1).forEach(p=>c.lineTo(p.x,p.y));[...right].reverse().forEach(p=>c.lineTo(p.x,p.y));c.closePath();c.fillStyle=fill;c.strokeStyle=fill;c.lineWidth=1.6;c.fill();c.stroke();c.restore()};
      type WorldPoint={x:number;z:number};
      const pushWorld=(points:WorldPoint[],x:number,depth:number)=>{const point={x:x*.1,z:depth},previous=points.at(-1);if(!previous||Math.abs(previous.x-point.x)>1e-7||Math.abs(previous.z-point.z)>1e-7)points.push(point)};
      const laneCenters=(lane:Lane,start:number,end:number)=>{const centers:WorldPoint[]=[],points=lane.points;for(let index=0;index<points.length;index++){const point=points[index];if(index){const previous=points[index-1],from=Math.max(start,previous.tick),to=Math.min(end,point.tick);if(to>=from&&point.tick>previous.tick){const count=Math.max(1,Math.min(120,Math.ceil(Math.abs(z(to)-z(from))/.35)));for(let part=0;part<=count;part++){const tick=from+(to-from)*part/count,amount=(tick-previous.tick)/(point.tick-previous.tick);pushWorld(centers,previous.xRear+(point.xFore-previous.xRear)*amount,z(tick))}}}if(point.tick>=start&&point.tick<=end){pushWorld(centers,point.xFore,z(point.tick));pushWorld(centers,point.xRear,z(point.tick))}}return centers};
      const simpleCenters=(start:number,end:number,x0:number,x1:number)=>{const centers:WorldPoint[]=[],count=Math.max(2,Math.min(120,Math.ceil(Math.abs(z(end)-z(start))/.35)));for(let part=0;part<=count;part++){const amount=part/count,tick=start+(end-start)*amount;pushWorld(centers,x0+(x1-x0)*amount,z(tick))}return centers};
      const orientedStrip=(centers:WorldPoint[],widthX:number,widthZ:number)=>{const left:{x:number;y:number}[]=[],right:{x:number;y:number}[]=[];if(centers.length<2)return{left,right};const halfX=widthX*.5,halfZ=widthZ*.5,normalised=centers.map(point=>({x:point.x/halfX,z:point.z/halfZ})),directions=normalised.slice(0,-1).map((point,index)=>{const next=normalised[index+1],dx=next.x-point.x,dz=next.z-point.z,length=Math.hypot(dx,dz)||1;return{x:dx/length,z:dz/length}});for(let index=0;index<centers.length;index++){let offset:{x:number;z:number};if(index===0){const direction=directions[0];offset={x:-direction.z,z:direction.x}}else if(index===centers.length-1){const direction=directions.at(-1)!;offset={x:-direction.z,z:direction.x}}else{const previous=directions[index-1],next=directions[index],cross=previous.x*next.z-previous.z*next.x;if(Math.abs(cross)<1e-7)offset={x:-previous.z,z:previous.x};else offset={x:(next.x-previous.x)/cross,z:(next.z-previous.z)/cross}}const point=centers[index],l=projectZ(point.z+offset.z*halfZ,(point.x+offset.x*halfX)*10),r=projectZ(point.z-offset.z*halfZ,(point.x-offset.x*halfX)*10);if(l&&r){left.push(l);right.push(r)}}return{left,right}};
      const fieldL:{x:number;y:number}[]=[],fieldR:{x:number;y:number}[]=[];for(let tick=Math.max(0,currentTick-t.resolution);tick<=visibleEnd;tick+=Math.max(1,t.resolution/24)){const b=bounds(tick),l=project(tick,b[0]),r=project(tick,b[1]);if(l&&r){fieldL.push(l);fieldR.push(r)}}ribbon(fieldL,fieldR,"#121928",1);
      const step=Math.max(1,t.resolution/2);for(let tick=Math.max(0,Math.floor(currentTick/step)*step);tick<=visibleEnd;tick+=step){const b=bounds(tick),l=project(tick,b[0]),r=project(tick,b[1]);if(!l||!r)continue;const major=Math.round(tick)%(t.resolution*4)===0;c.strokeStyle=major?"rgba(150,171,218,.51)":"rgba(150,171,218,.20)";c.lineWidth=major?2.4:1.2;c.beginPath();c.moveTo(l.x,l.y);c.lineTo(r.x,r.y);c.stroke()}
      const clip=(a:number,b:number)=>{if(b<=a||z(b)<JUDGE||z(a)>FAR)return null;return[z(a)<JUDGE?tickAtZ(a,b,JUDGE):a,z(b)>FAR?tickAtZ(a,b,FAR):b] as const};
      const holdKeepEffects:{x:number;wall:boolean;critical:boolean}[]=[];
      const wallPressAmp=(kind:string)=>{const note=preview.notes.find(item=>item.kind==="Hold"&&item.laneKind===kind&&currentTick>=item.tick&&currentTick<(item.endTick||item.tick));if(!note)return 1;const frames=Math.max(1,(state.seconds-t.secondsAtTick(note.tick))*60);return 1+1/(1+(frames-1)*.6)};
      const drawLane=(lane:Lane)=>{if(lane.points.length<2)return;const range=clip(lane.points[0].tick,lane.points[lane.points.length-1].tick);if(!range)return;const beamWidths:Record<number,number>={0:.2,1:.2,2:.3,3:.4,4:1.2,5:2},isWall=lane.kind.includes("Wall"),pressAmp=isWall?wallPressAmp(lane.kind):1,widthX=lane.kind==="Beam"?(beamWidths[lane.beamWidthId||0]||.2):(isWall?.24*pressAmp:.08),widthZ=lane.kind==="Beam"?widthX:(isWall?.45*pressAmp:.2),{left,right}=orientedStrip(laneCenters(lane,range[0],range[1]),widthX,widthZ),color=lane.kind==="Colorful"?colorful[Math.abs(lane.colorId??0)%colorful.length]:(colors[lane.kind]||colors.Beam),brightness=lane.kind==="Colorful"?Math.max(.38,Math.min(1,1-(lane.brightnessId||0)*.08)):1;if(lane.kind==="Beam"){c.save();c.shadowColor="#d94cff";c.shadowBlur=18;ribbon(left,right,"#8b30d5",.42);const innerL=left.map((p,i)=>({x:p.x+(right[i].x-p.x)*.28,y:p.y})),innerR=right.map((p,i)=>({x:p.x+(left[i].x-p.x)*.28,y:p.y}));ribbon(innerL,innerR,"#ed6dff",.82);c.restore()}else{ribbon(left,right,color,.34*brightness);const innerL=left.map((p,i)=>({x:p.x+(right[i].x-p.x)*.22,y:p.y})),innerR=right.map((p,i)=>({x:p.x+(left[i].x-p.x)*.22,y:p.y}));ribbon(innerL,innerR,color,.9*brightness)}};
      const bar=(n:Note,tick:number,x:number,alpha=1,end=false)=>{const p=project(tick,x),leftWall=n.laneKind==="LeftWall",rightWall=n.laneKind==="RightWall",wall=leftWall||rightWall,l=project(tick,x-(wall?1.2:3)),r=project(tick,x+(wall?1.2:3));if(!p||!l||!r)return;const width=Math.max(8,Math.abs(r.x-l.x));c.save();c.globalAlpha=alpha;if(wall){const inward=leftWall?1:-1,height=Math.max(24,Math.min(112,width*3.15)),horizontalAspectCorrection=previewZoom/horizontalZoom,capWidth=height*.54*horizontalAspectCorrection,outer=p.x-inward*capWidth*.5,outerShoulder=p.x-inward*capWidth*.28,innerShoulder=p.x+inward*capWidth*.12,tip=p.x+inward*capWidth*.52,top=p.y-height*.5,bottom=p.y+height*.5,sideGlow=leftWall?"#7b4dff":"#ff54d5";c.beginPath();c.moveTo(outer,p.y-height*.34);c.lineTo(outerShoulder,top);c.lineTo(innerShoulder,top);c.lineTo(tip,p.y);c.lineTo(innerShoulder,bottom);c.lineTo(outerShoulder,bottom);c.lineTo(outer,p.y+height*.34);c.closePath();c.shadowColor=sideGlow;c.shadowBlur=Math.max(n.isCritical?14:8,height*(n.isCritical?.22:.14));c.strokeStyle=leftWall?`rgba(126,101,255,${n.isCritical?.9:.55})`:`rgba(255,70,188,${n.isCritical?.9:.55})`;c.lineWidth=Math.max(n.isCritical?9:7,height*(n.isCritical?.11:.085));c.stroke();c.shadowBlur=0;const body=c.createLinearGradient(0,top,0,bottom);if(leftWall){body.addColorStop(0,"rgba(127,76,255,.9)");body.addColorStop(.52,"rgba(72,26,192,.78)");body.addColorStop(1,"rgba(103,49,238,.92)")}else{body.addColorStop(0,"rgba(255,91,207,.9)");body.addColorStop(.52,"rgba(174,32,150,.78)");body.addColorStop(1,"rgba(235,55,190,.92)")}c.fillStyle=body;c.fill();c.strokeStyle=n.isCritical?"#fff":"rgba(236,226,255,.98)";c.lineWidth=Math.max(2,height*(n.isCritical?.034:.026));c.stroke();c.strokeStyle="rgba(250,245,255,.96)";c.lineWidth=Math.max(2,height*.078);c.beginPath();c.moveTo(p.x-inward*capWidth*.27,p.y);c.lineTo(p.x+inward*capWidth*.27,p.y);c.stroke();c.restore();return}const prefix=n.laneKind==="Left"?"mu3_nt_tap":n.laneKind==="Right"?"mu3_nt_hold":"mu3_nt_extap",img=sprites[`${prefix}_02.png`];if(img){const height=Math.max(7,Math.min(38,width*img.height/img.width));if(n.isCritical){c.shadowColor="#fff";c.shadowBlur=Math.max(10,height*.8);c.globalAlpha=alpha*.9;c.drawImage(img,p.x-width*.54,p.y-height*.62,width*1.08,height*1.24);c.shadowBlur=0}c.globalAlpha=alpha*(end?.78:1);c.drawImage(img,p.x-width/2,p.y-height/2,width,height);c.restore();return}const height=Math.max(5,Math.min(30,width*.16));c.fillStyle=colors[n.laneKind||"Center"]||colors.Center;c.strokeStyle="#fff";c.lineWidth=2;c.beginPath();c.roundRect(p.x-width/2,p.y-height/2,width,height,height*.32);c.fill();c.stroke();c.restore()};
      const isSideNote=(n:Note)=>n.laneKind==="LeftWall"||n.laneKind==="RightWall";
      const showNote=(n:Note)=>n.kind==="Bell"?displayOptions.bell:n.kind==="Bullet"?displayOptions.bullets:n.kind==="Tap"||n.kind==="Hold"||n.kind==="Flick"?isSideNote(n)?displayOptions.side:displayOptions.floor:true;
      if(displayOptions.lanes)preview.lanes.filter(l=>l.kind!=="Beam").forEach(drawLane);
      for(const n of preview.notes){if(!showNote(n)||n.kind!=="Hold"||(n.endTick||0)<visibleStart||n.tick>visibleEnd)continue;const range=clip(n.tick,n.endTick||n.tick);if(!range)continue;const lane=preview.lanes.find(l=>l.id===n.laneId&&l.kind!=="Beam"),wall=n.laneKind==="LeftWall"||n.laneKind==="RightWall",centers=lane?laneCenters(lane,range[0],range[1]):simpleCenters(range[0],range[1],n.x,n.endX??n.x);if(centers.length){if(Math.abs(range[0]-n.tick)<1e-6)centers[0].x=n.x*.1;if(Math.abs(range[1]-(n.endTick||n.tick))<1e-6)centers[centers.length-1].x=(n.endX??n.x)*.1}const{left,right}=orientedStrip(centers,.6,.6),holdColor=colors[n.laneKind||"Center"]||colors.Center,judging=currentTick>=n.tick&&currentTick<(n.endTick||n.tick),pulse=judging?.72+.18*Math.sin(state.seconds*18):.58;ribbon(left,right,holdColor,wall?.86:pulse);const innerL=left.map((p,i)=>({x:p.x+(right[i].x-p.x)*(wall?.27:.35),y:p.y})),innerR=right.map((p,i)=>({x:p.x+(left[i].x-p.x)*(wall?.27:.35),y:p.y}));if(wall){c.save();c.shadowColor=n.laneKind==="LeftWall"?"#a994ff":"#ff8fdc";c.shadowBlur=judging?18:9;ribbon(innerL,innerR,n.laneKind==="LeftWall"?"#ddd6ff":"#ffd5ef",judging?.92:.58);c.restore()}else ribbon(innerL,innerR,"#f5fff9",judging?.42:.22);if(displayOptions.effects&&judging)holdKeepEffects.push({x:lane?laneX(lane,currentTick):n.x+((n.endX??n.x)-n.x)*(currentTick-n.tick)/Math.max(1,(n.endTick||n.tick)-n.tick),wall,critical:!!n.isCritical});if(n.endTick&&z(n.endTick)>=JUDGE&&z(n.endTick)<=FAR)bar(n,n.endTick,n.endX??n.x,.9,true)}
      if(displayOptions.lanes)preview.lanes.filter(l=>l.kind==="Beam").forEach(drawLane);
      for(let i=lowerNotes(preview.notes,visibleStart);i<preview.notes.length;i++){const n=preview.notes[i];if(n.tick>visibleEnd)break;if(!showNote(n)||z(n.tick)<JUDGE-.65||z(n.tick)>FAR+.65)continue;if(n.kind==="Tap"||n.kind==="Hold"){bar(n,n.tick,n.x);continue}const p=project(n.tick,n.x),a=project(n.tick,n.x-1),b=project(n.tick,n.x+1);if(!p)continue;const radius=(a&&b?Math.max(7,Math.abs(b.x-a.x)/2):7)*(n.isLargeBullet?1.4:1);if(n.kind==="Bell"){const spin=state.seconds*2.3;c.save();c.translate(p.x,p.y);c.rotate(spin);c.shadowColor="#ffd94c";c.shadowBlur=radius*1.25;for(let ray=0;ray<8;ray++){c.rotate(Math.PI/4);c.fillStyle="rgba(255,224,82,.48)";c.fillRect(radius*.72,-1.2,radius*.78,2.4)}c.rotate(Math.PI/4);c.fillStyle="#fff7a8";c.strokeStyle="#ffb51f";c.lineWidth=2.2;c.beginPath();c.moveTo(0,-radius);c.lineTo(radius*.82,0);c.lineTo(0,radius);c.lineTo(-radius*.82,0);c.closePath();c.fill();c.stroke();c.fillStyle="#fff";c.beginPath();c.arc(0,0,radius*.3,0,Math.PI*2);c.fill();c.restore()}else if(n.kind==="Bullet"){const strength=n.bulletStrength||"Normal",palette=strength==="Danger"?{core:"#14151c",edge:"#f5f7ff",glow:"#ffffff"}:strength==="Hard"?{core:"#7328a6",edge:"#e893ff",glow:"#c853ff"}:{core:"#b91f35",edge:"#ff8c8c",glow:"#ff334f"};c.save();c.translate(p.x,p.y);c.shadowColor=palette.glow;c.shadowBlur=radius*.9;c.fillStyle=palette.core;c.strokeStyle=palette.edge;c.lineWidth=Math.max(2,radius*.16);if(n.bulletShape==="Needle"){c.rotate(Math.atan2(p.y-(projectZ(JUDGE,n.x)?.y||p.y+1),p.x-(projectZ(JUDGE,n.x)?.x||p.x)));c.beginPath();c.moveTo(radius*1.65,0);c.lineTo(-radius*.8,-radius*.55);c.lineTo(-radius*.45,0);c.lineTo(-radius*.8,radius*.55);c.closePath()}else if(n.bulletShape==="Square"){c.rotate(Math.PI/4);c.beginPath();c.roundRect(-radius*.76,-radius*.76,radius*1.52,radius*1.52,radius*.18)}else{c.beginPath();for(let k=0;k<16;k++){const rr=k%2?radius*.82:radius*1.12,ang=k*Math.PI/8;c.lineTo(Math.cos(ang)*rr,Math.sin(ang)*rr)}c.closePath()}c.fill();c.stroke();c.fillStyle=palette.edge;c.beginPath();c.arc(0,0,radius*.25,0,Math.PI*2);c.fill();c.restore()}else if(n.kind==="Flick"){const size=Math.max(16,radius*3.3),d=n.isRight?1:-1,img=sprites["mu3_nt_flicktap_00.png"];c.save();c.translate(p.x,p.y);if(img){c.shadowColor=n.isCritical?"#fff":"#43e9ff";c.shadowBlur=n.isCritical?18:9;c.drawImage(img,-size*.34,-size*.42,size*.68,size*.84);c.shadowBlur=0}c.strokeStyle=n.isCritical?"#fff":"#76f4ff";c.lineWidth=Math.max(2,size*.07);c.lineCap="square";for(let q=0;q<2;q++){const x=d*(size*(.08+q*.2));c.beginPath();c.moveTo(x-d*size*.15,-size*.22);c.lineTo(x+d*size*.1,0);c.lineTo(x-d*size*.15,size*.22);c.stroke()}c.restore()}}
      const effectWidth=(x:number,half=3)=>{const l=projectZ(JUDGE,x-half),r=projectZ(JUDGE,x+half);return l&&r?Math.max(34,Math.abs(r.x-l.x)):58};
      const effectWorldWidth=(x:number,worldWidth:number)=>effectWidth(x,worldWidth*5);
      const effectGroundSize=(x:number,worldWidth:number,worldDepth:number)=>{const left=projectZ(JUDGE,x-worldWidth*5),right=projectZ(JUDGE,x+worldWidth*5),near=projectZ(JUDGE-worldDepth*.5,x),far=projectZ(JUDGE+worldDepth*.5,x);return{width:left&&right?Math.max(1,Math.abs(right.x-left.x)):effectWorldWidth(x,worldWidth),height:near&&far?Math.max(1,Math.abs(far.y-near.y)):effectWorldWidth(x,worldDepth)}};
      const groundStamp=(name:string,x:number,y:number,noteX:number,worldWidth:number,worldDepth:number,alpha:number,rotation=0,color="#ffffff")=>{const size=effectGroundSize(noteX,worldWidth,worldDepth);return stamp(name,x,y,size.width,size.height,alpha,rotation,color)};
      const drawTapImpact=(n:Note,age:number)=>{const duration=reducedMotion?.12:.3;if(age<0||age>duration)return;const p=projectZ(JUDGE,n.x);if(!p)return;const accent=n.isCritical?"#ffffff":n.laneKind==="LeftWall"?"#9a82ff":n.laneKind==="RightWall"?"#ff83da":"#9ff4ff",loaded=!!effectSprites["FX_hy_00_119"];if(loaded){if(age<=.1){const coreProgress=age/.1,coreScale=.38+.62*(1-Math.pow(1-coreProgress,2));groundStamp("FX_hy_00_119",p.x,p.y,n.x,2.24*coreScale,1.056*coreScale,Math.pow(1-coreProgress,.7),0,accent)}const waveProgress=Math.min(1,age/.3),waveScale=.204+.796*(1-Math.pow(1-waveProgress,2.4));groundStamp("FX_hy_00_202",p.x,p.y,n.x,2.8*waveScale,1.32*waveScale,Math.pow(1-waveProgress,1.35),0,n.isCritical?"#ffffff":"#d8fbff");return}const q=1-age/duration,size=effectGroundSize(n.x,2.24,1.056);c.save();c.translate(p.x,p.y);c.globalCompositeOperation="lighter";c.globalAlpha=q*q;c.fillStyle=accent;c.beginPath();c.ellipse(0,0,size.width*.5,size.height*.5,0,0,Math.PI*2);c.fill();c.restore()};
      const drawFlickImpact=(n:Note,age:number)=>{const duration=reducedMotion?.18:.72;if(age<0||age>duration)return;const p=projectZ(JUDGE,n.x);if(!p)return;const q=1-age/duration,ease=1-q*q*q,d=n.isRight?1:-1,width=effectWidth(n.x,3),accent=n.isCritical?"#ffffff":"#79efff";if(effectSprites["FX_hy_01_101"]){c.save();c.translate(p.x,p.y);c.scale(d,1);stamp("FX_hy_00_103",0,0,width*(.9+ease*.5),width*(.24+ease*.12),q*q,0,accent);stamp("FX_hy_01_101",width*ease*.52,-width*.05,width*(.7+ease*1.2),width*(.38+ease*.54),q*.84,-.08,accent);if(!reducedMotion){for(let gate=0;gate<3;gate++)stamp(gate===0?"FX_hy_00_246":"FX_hy_00_243",width*(.18+ease*(.42+gate*.23)),0,width*(.46+ease*(.62+gate*.2)),width*(.2+ease*(.24+gate*.08)),q*(.76-gate*.12),0,accent);stamp("FX_hy_00_144",width*ease*.28,0,width*(.65+ease*.95),width*(.24+ease*.34),q*.62,0,accent)}c.restore();return}c.save();c.translate(p.x,p.y);c.scale(d,1);c.globalCompositeOperation="lighter";c.globalAlpha=q*q;c.strokeStyle=accent;c.lineWidth=Math.max(2,width*.05);c.beginPath();c.moveTo(-width*.2,-width*.2);c.lineTo(width*(.3+ease),0);c.lineTo(-width*.2,width*.2);c.stroke();c.restore()};
      const drawHoldKeep=(item:{x:number;wall:boolean;critical:boolean})=>{const p=projectZ(JUDGE,item.x);if(!p)return;const pulse=.94+.06*Math.sin(state.seconds*15),accent=item.critical?"#ffffff":"#b9f8ff",size=effectGroundSize(item.x,2.5*pulse,2.5*pulse);if(effectSprites["FX_hy_00_102"]){stamp("FX_hy_00_102",p.x,p.y,size.width,size.height,.72,0,accent);stamp("FX_hy_00_202",p.x,p.y,size.width,size.height,.42,0,"#eaffff");return}c.save();c.translate(p.x,p.y);c.globalCompositeOperation="lighter";c.globalAlpha=.7;c.fillStyle=accent;c.beginPath();c.ellipse(0,0,size.width*.5,size.height*.5,0,0,Math.PI*2);c.fill();c.restore()};
      const drawHoldRelease=(n:Note,age:number)=>{const duration=reducedMotion?.22:.5;if(age<0||age>duration)return;const x=n.endX??n.x,p=projectZ(JUDGE,x);if(!p)return;const accent=n.isCritical?"#ffffff":"#d8fbff";if(effectSprites["FX_hy_01_101"]){if(age<=.3){const launchProgress=age/.3,launchScale=1-Math.pow(1-launchProgress,2.4);groundStamp("FX_hy_00_202",p.x,p.y,x,7*launchScale,3.5*launchScale,Math.pow(1-launchProgress,.72),0,accent)}const shineProgress=Math.min(1,age/.5),shineScale=Math.max(0,shineProgress<.14?.677+(1-.677)*(shineProgress/.14):shineProgress<.368?1-(1-.44)*((shineProgress-.14)/.228):.44*(1-(shineProgress-.368)/.632));groundStamp("FX_hy_01_101",p.x,p.y,x,10*shineScale,10*shineScale,Math.pow(1-shineProgress,.82),0,accent);return}const q=1-age/duration,size=effectGroundSize(x,7,3.5);c.save();c.translate(p.x,p.y);c.globalCompositeOperation="lighter";c.globalAlpha=q*q;c.strokeStyle=accent;c.lineWidth=Math.max(2,size.width*.02);c.beginPath();c.ellipse(0,0,size.width*.5,size.height*.5,0,0,Math.PI*2);c.stroke();c.restore()};
      const drawBellCatch=(n:Note,age:number)=>{const duration=reducedMotion?.18:.9;if(age<0||age>duration)return;const p=projectZ(JUDGE,n.x);if(!p)return;const q=1-age/duration,ease=1-q*q*q,width=effectWidth(n.x,2.2),gold="#ffd94f",pale="#fff4a6";if(effectSprites["FX_hy_00_114"]){stamp("FX_hy_00_114",p.x,p.y,width*(.54+ease*1.46),width*(.16+ease*.42),q*.84,0,gold);stamp("FX_hy_00_917",p.x-width*ease*.14,p.y-width*ease*.06,width*(.42+ease*.74),width*(.2+ease*.36),q*.55,-age*.4,pale);stamp("FX_hy_01_103",p.x,p.y,width*(.36+ease*.92),width*(.22+ease*.62),q*.78,age*.3,pale);if(!reducedMotion){for(let particle=0;particle<8;particle++){const a=particle*Math.PI/4+age*1.7,dist=width*(.16+ease*(.34+(particle%2)*.15));stamp("FX_hy_13_401",p.x+Math.cos(a)*dist,p.y+Math.sin(a)*dist*.42,width*.11,width*.11,q*.72,a,gold)}}return}c.save();c.translate(p.x,p.y);c.globalCompositeOperation="lighter";c.globalAlpha=q*q;c.strokeStyle=pale;c.lineWidth=Math.max(2,width*.035);c.beginPath();c.ellipse(0,0,width*(.18+ease*.72),width*(.07+ease*.22),0,0,Math.PI*2);c.stroke();c.restore()};
      const judge=projectZ(JUDGE,0)!,far=projectZ(FAR,0)!,maskLeft=logicalCenter-backgroundHalfWidth,maskWidth=backgroundHalfWidth*2;c.fillStyle=bg;c.fillRect(maskLeft,0,maskWidth,Math.max(0,far.y));c.fillRect(maskLeft,Math.max(0,judge.y),maskWidth,VH);if(displayOptions.effects){c.save();c.beginPath();c.rect(maskLeft,0,maskWidth,Math.max(0,judge.y+4));c.clip();for(const item of holdKeepEffects)drawHoldKeep(item);for(let i=lowerNotes(preview.notes,currentTick-t.resolution*2);i<preview.notes.length;i++){const n=preview.notes[i];if(n.tick>currentTick+1)break;const age=state.seconds-t.secondsAtTick(n.tick);if(n.kind==="Tap"||n.kind==="Hold")drawTapImpact(n,age);else if(n.kind==="Flick")drawFlickImpact(n,age);else if(n.kind==="Bell")drawBellCatch(n,age)}for(let i=lowerNotes(holdEnds,currentTick-t.resolution*2);i<holdEnds.length;i++){const item=holdEnds[i];if(item.tick>currentTick+1)break;drawHoldRelease(item.note,state.seconds-t.secondsAtTick(item.tick))}c.restore()}const bb=bounds(currentTick),jl=projectZ(JUDGE,bb[0]),jr=projectZ(JUDGE,bb[1]);if(jl&&jr){c.save();c.beginPath();c.rect(maskLeft,0,maskWidth,Math.max(0,judge.y));c.clip();c.strokeStyle="rgba(255,92,54,.28)";c.lineWidth=28;c.beginPath();c.moveTo(jl.x,jl.y);c.lineTo(jr.x,jr.y);c.stroke();c.restore();c.strokeStyle="#ff7041";c.lineWidth=6;c.beginPath();c.moveTo(jl.x,jl.y);c.lineTo(jr.x,jr.y);c.stroke()}c.restore();frame=requestAnimationFrame(draw)};
    frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);observer.disconnect()}
  },[displayOptions,effectSprites,holdEnds,preview,snapshot,sprites,t]);
  return <canvas ref={ref} className="chart-canvas" aria-label="谱面预览"/>
}
